POST http://192.168.1.109:5000/api/macro
Content-Type: application/json

{
  "arrayMacrotopic": [
    { "quantitySelected": 3, "macroID": 1 },
    { "quantitySelected": 5, "macroID": 2 },
    { "quantitySelected": 6, "macroID": 3 },
    { "quantitySelected": 4, "macroID": 4 },
    { "quantitySelected": 2, "macroID": 5 }
  ]
}
