GET http://localhost:5000/api/user/
Content-Type: application/json


###----------------------------------------------------------------------------------
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "name": "sono un test user",
  "email": "spin.fa2bio2012@gmail.com",
  "password": "miapasswordona"
}



###----------------------------------------------------------------------------------

POST http://localhost:5000/api/user/login
Content-Type: application/json

{
  "name": "sono un test user",
  "email": "spin.fabio20@gmail.com",
  "password": "miapasswordona",
  "uuid":"3a3239c5-0121-4515-9ea3-08248b70aabd"
}

###----------------------------------------------------------------------------------

POST http://localhost:5000/api/user/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJzb25vIHVuIHRlc3QgdXNlciIsImVtYWlsIjoic3Bpbi5mYWJpbzIwQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMxMjQ0ODg3LCJleHAiOjE3MzEyNDUxODd9.edkKIh8Wb4VBpxMHKk8qPTpFnZQKdIX4T3OU1JYG3EA
Cookie: uuid=3a3239c5-0121-4515-9ea3-08248b70aabd

{
  "message": "ciaone",
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJzb25vIHVuIHRlc3QgdXNlciIsImVtYWlsIjoic3Bpbi5mYWJpbzIwQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMxMDg3ODg1LCJleHAiOjE3MzEwODgxODV9.WCeJbgb2Ja8E1uepkGz86IwLb9FxVCJ-W_JUWyxPBGk"
}


###----------------------------------------------------------------------------------

GET http://localhost:5000/api/user/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJzb25vIHVuIHRlc3QgdXNlciIsInJvbGUiOiJ1c2VyIiwiZW1haWwiOiJzcGluLmZhYmlvMjBAZ21haWwuY29tIiwiaWF0IjoxNzMxMjQ2MTc1LCJleHAiOjE3MzE4NTA5NzV9.-FzRaaCnjDrWWyieX9mkNYhzDw-nl2DmQMJbxJu7DKA
Cookie: uuid=3a3239c5-0121-4515-9ea3-08248b70aabd
